# Parameters used to generate this table
# Generated: 2026-01-20T22:17:04.016172

score_name: Margin
baseline:
  postprocessor: margin
  run_tag: margin-grid-20260120
  selection: best on res (minimize FPR@95)
partition:
  run_tag: margin-unif-mass-grid-20260120
  alpha: 0.05
  score: upper
  k_selection: rice_rule
  rice_k: {'cifar10': 30, 'cifar100': 30, 'imagenet': 50}
n_seeds: 9
results_dir: results