# Parameters used to generate plots in this folder
# Generated: 2026-01-21T00:56:04.521971

score_name: doctor
baseline_run_tag: doctor-grid-20260120
partition_run_tag: doctor-unif-mass-sim-grid-20260120
n_seeds: 9
results_dir: results