# Parameters used to generate plots in this folder
# Generated: 2026-01-21T00:10:14.607521

score_name: margin
baseline_run_tag: margin-grid-20260120
partition_run_tag: margin-unif-mass-sim-grid-20260120
n_seeds: 9
results_dir: results